language: go
go:
  - 1.9

services:
  - docker

#cache:
#  directories:
#  - "$GOPATH/src"
#  - "$GOPATH/pkg"
#  - "$HOME/gopath/src/github.com/$TRAVIS_REPO_SLUG"

stages:
  - name: development
  - name: deploy

jobs:
  include:
  - stage: development
    script: make development

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: IoDm4GzP8zoNCYgn5s3JoU75QgO4miRLwdm3jiRN+OOGdIFC56roSUmJlpzyujNyyptuG+8Z6ZuxZ0sCZE13Cmd+4BwryJ2DvWe61AUvTtj1006ZTP3VIHbdJ4XYkGCF8V38ZlWXK/GjzvyY9aONkkrzh6zlzoiRmgr7G8SSlXqvdmU9np95Vslktq+dlc/67gSxWxtSP1mTtkxP9GXImXTMhOO3RmQpDaL4BQv0HcQHhy33GQXCoGWYGJ/DKwxfCdyBqrwD2OIGPRaS0elPyChN7fJSWz0Uz5j1SshkapkzpsdTdSvJ0QFACjuuVR7NURVMqIsneaTsaSYRNiVCZT2v6PQktBO8WZVOCwZJYHteJArZ9ps5pYuBCTjmpccDSyLW2srGNPSgUm7hyyAlmHOycOsuT9skemlXPqNMUV02SlYZyafQVZQXyeMVTgd0/14Vw+WrRpMRVQrIdn+DaNe6VqVOCbS4dZzdoLgsAnZgcgvjEzMXepLbC2YJv96C7I5RDXeKFxCdUJBbh4oiFLnq33eJIus4R2c/1BtyT2ngvO0bHPK9ujKtnVYK7InmfoQvxH72zCySUslMkAfz1Iu/BiZgzzubjOE6+3qwUvT1RtD0WBIxJUzqvfkjppREV1fibI7GTWtNRlZ4TzcA1685Us+P15AMxnCWnvDnIOs=
    tag_name: $TRAVIS_TAG
    name: Build $(date +'%d.%m.%Y %R')
    file_glob: true
    file:
      - build/*
    on:
      repo: wesovilabs/mollydb
      branch: master
      tags: true
  - provider: script
    skip_cleanup: true
    script: make release
    on:
      repo: wesovilabs/mollydb
      branch: master
      tags: true

notifications:
  email: false

env:
  global:
  - secure: JJxRmkGmkK3hMbOnbViNXpjGDpJ9JkQq7tvuTppu7pwV6UnK/1PgUpQSYBmmsCQwzUhfKAykZT5mDvH0fQOd8GwmtX+uDFzn6yguX6lFGhGGyODJFlOry0h7az/ATc9m4v66sd2+23pYLWFG3iMlzwbwTCpqfdgs/fVMn5Ef4lzvz9HlLSKQEeM8Pbda3LbZ1adra4RBQ7H6N7y43+7RWbEjIkVaLdw19eeaqpPIEi3kUfJoBBXnc6OofR0c3aHRUKDgjb7P5W3PlAeh/BjxuItFoR1446sz4g/pL36jVivpKGMN6aSDeB+JaWpBiO6JPFtEoOPgNxzZoWS4905TyYx22EYsiogy7sV0z4zqNKG+KGSF9UA7RiyxDbct7rs8+FuXGd/jXlKtFMbIwP7YWpiSZ752HiLtDoURL1GtqKwNzhLyGxMoHLr9pO9aSzlnz3lfoouGdKfvaY4PPUY4gYl5e/6GZjhxqNhryX94UEN+0VQsQ+jolxTBFxwWnZCff+xsRvJs6/vk0SUtztC6snJuhZmA2Mfz0eK3pOIXU9LbvR130zCBOnvzMrMCZPg128Zzdj6YoBSnYRNrkvgNv2684/qz5JCT9w8Ly/jhC8iq2tOg4sv/OpAUB3zbj91z3GoKZeT8bVuUTpRUcNnrBSQ1FW/XwutCDZ7S9eXQkdU=
  - secure: E324/wdZExB1ja0UBwfYZP2wq+pkK7Gm+AoeEvsRa6VjE4oUvdad07qCJYbR4uOa9K9htE2dW6+WHuziaWM/1E25Zc+hG1Q9GUDvuxYBoKzBZlwqGPJS3U4GgP0Csmzx5LSgXrGhy+/ScCvB2i0MRv5KHlJFJCwu7ea/AE7ADE2r86Xm+2xukfNj0aQozVGAnt+uDmAAuRYJgbJ8HUO4NFFJL1yU21pEEZ8rSgE8TNuzYf70O+35pq+JO54ld+etAKQuE9MOV7R60Zwy/0SqRYDPGm/Crlb6/ZeEq9puLejfy75A7pPV5CBjn+wHHOqV1TNDBz5dMozVJOi1f5Wiit8k6oFgolhJ0nHlEP+DTI5DjAR9af4yoj9Nn6Gm7TFjEabhhFLnIW1MMmZFITA/mNkOkOk8XaN4wFS9+nXtn/c4ISoM+OeBy0zdJBYF+qyQikTc3QaIsCn3dPJpdqRJVC/RY5zFkK/1MgDG898m7Ts/NX+bLm8P2kkfac20vs4UyAuNx+YQe7ejOx5AD3td/HSKUsH/1ycPeVXHloVxsA3h1TzKd7oHO51x6HdkBgIIlHIfI8y8W1GEOQROVPxc7iigV1oPEGA0jxQTUoNH63JhGvz7WUST5HfLTgCg2lbFZA4XNGmTxF3VsgOjFCAAK98l0/G5TPho+FgBjYErXHI=
